//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MSdbm
    {
        public MSdbm()
        {
            this.MSdbms_datatype = new HashSet<MSdbms_datatype>();
            this.MSdbms_map = new HashSet<MSdbms_map>();
            this.MSdbms_map1 = new HashSet<MSdbms_map>();
        }
    
        public int dbms_id { get; set; }
        public string dbms { get; set; }
        public string version { get; set; }
    
        public virtual ICollection<MSdbms_datatype> MSdbms_datatype { get; set; }
        public virtual ICollection<MSdbms_map> MSdbms_map { get; set; }
        public virtual ICollection<MSdbms_map> MSdbms_map1 { get; set; }
    }
}
