//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class syscollector_collector_types_internal
    {
        public syscollector_collector_types_internal()
        {
            this.syscollector_collection_items_internal = new HashSet<syscollector_collection_items_internal>();
        }
    
        public System.Guid collector_type_uid { get; set; }
        public string name { get; set; }
        public string parameter_schema { get; set; }
        public string parameter_formatter { get; set; }
        public string schema_collection { get; set; }
        public string collection_package_name { get; set; }
        public System.Guid collection_package_folderid { get; set; }
        public string upload_package_name { get; set; }
        public System.Guid upload_package_folderid { get; set; }
        public bool is_system { get; set; }
    
        public virtual ICollection<syscollector_collection_items_internal> syscollector_collection_items_internal { get; set; }
        public virtual sysssispackage sysssispackage { get; set; }
        public virtual sysssispackage sysssispackage1 { get; set; }
    }
}
