//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysdtssteplog
    {
        public sysdtssteplog()
        {
            this.sysdtstasklogs = new HashSet<sysdtstasklog>();
        }
    
        public long stepexecutionid { get; set; }
        public System.Guid lineagefull { get; set; }
        public string stepname { get; set; }
        public Nullable<int> stepexecstatus { get; set; }
        public Nullable<int> stepexecresult { get; set; }
        public System.DateTime starttime { get; set; }
        public Nullable<System.DateTime> endtime { get; set; }
        public Nullable<double> elapsedtime { get; set; }
        public Nullable<int> errorcode { get; set; }
        public string errordescription { get; set; }
        public Nullable<long> progresscount { get; set; }
    
        public virtual sysdtspackagelog sysdtspackagelog { get; set; }
        public virtual ICollection<sysdtstasklog> sysdtstasklogs { get; set; }
    }
}
