//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysdtspackagelog
    {
        public sysdtspackagelog()
        {
            this.sysdtssteplogs = new HashSet<sysdtssteplog>();
        }
    
        public string name { get; set; }
        public string description { get; set; }
        public System.Guid id { get; set; }
        public System.Guid versionid { get; set; }
        public System.Guid lineagefull { get; set; }
        public int lineageshort { get; set; }
        public System.DateTime starttime { get; set; }
        public Nullable<System.DateTime> endtime { get; set; }
        public Nullable<double> elapsedtime { get; set; }
        public string computer { get; set; }
        public string @operator { get; set; }
        public System.DateTime logdate { get; set; }
        public Nullable<int> errorcode { get; set; }
        public string errordescription { get; set; }
    
        public virtual ICollection<sysdtssteplog> sysdtssteplogs { get; set; }
    }
}
