//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysdtstasklog
    {
        public long stepexecutionid { get; set; }
        public int sequenceid { get; set; }
        public int errorcode { get; set; }
        public string description { get; set; }
    
        public virtual sysdtssteplog sysdtssteplog { get; set; }
    }
}
