//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysmail_servertype
    {
        public sysmail_servertype()
        {
            this.sysmail_server = new HashSet<sysmail_server>();
        }
    
        public string servertype { get; set; }
        public bool is_incoming { get; set; }
        public bool is_outgoing { get; set; }
        public System.DateTime last_mod_datetime { get; set; }
        public string last_mod_user { get; set; }
    
        public virtual ICollection<sysmail_server> sysmail_server { get; set; }
    }
}
