//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CPS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class syssession
    {
        public syssession()
        {
            this.sysjobactivities = new HashSet<sysjobactivity>();
        }
    
        public int session_id { get; set; }
        public System.DateTime agent_start_date { get; set; }
    
        public virtual ICollection<sysjobactivity> sysjobactivities { get; set; }
    }
}
