//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CameraPingingSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class camera
    {
        public int ID { get; set; }
        public string IP_ADDRESS { get; set; }
        public Nullable<int> ROAD { get; set; }
        public Nullable<int> SECTOR { get; set; }
        public Nullable<int> GATE { get; set; }
        public Nullable<int> BOOTH { get; set; }
        public Nullable<int> LANE { get; set; }
    
        public virtual booth booth1 { get; set; }
        public virtual gate gate1 { get; set; }
        public virtual lane lane1 { get; set; }
        public virtual road road1 { get; set; }
        public virtual sector sector1 { get; set; }
    }
}
