//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CameraPingingSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class gate
    {
        public gate()
        {
            this.cameras = new HashSet<camera>();
        }
    
        public int ID { get; set; }
        public string NAME { get; set; }
    
        public virtual ICollection<camera> cameras { get; set; }
    }
}
