//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CameraPingingSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sector
    {
        public sector()
        {
            this.cameras = new HashSet<camera>();
            this.gates = new HashSet<gate>();
        }
    
        public int ID { get; set; }
        public string NAME { get; set; }
        public Nullable<int> road { get; set; }
    
        public virtual ICollection<camera> cameras { get; set; }
        public virtual ICollection<gate> gates { get; set; }
        public virtual road road1 { get; set; }
    }
}
